### ISSUE TITLE
OSError: [Errno 2] No such file or directory make_asset_dirs, os.symlink(source, target) 

### ISSUE THREAD

**Issue by pipech** [pipech/erpnext-docker-debian#15]
frappe@609ffc91c9aa:~/bench$ bench update --build                                                                                                 
	Traceback (most recent call last):                                                                                                                
	  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main                                                                            
		"__main__", fname, loader, pkg_name)                                                                                                          
	  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code                                                                                       
		exec code in run_globals                                                                                                                      
	  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>                                                        
		main()                                                                                                                                        
	  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main                                                            
		click.Group(commands=commands)(prog_name='bench')                                                                                             
	  File "/home/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__                                            
		return self.main(*args, **kwargs)                                                                                                             
	  File "/home/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 697, in main                                                
		rv = self.invoke(ctx)                                                                                                                         
	  File "/home/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke                                             
		return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                       
	  File "/home/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke                                             
		return _process_result(sub_ctx.command.invoke(sub_ctx))                                                                                       
	  File "/home/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke                                              
		return ctx.invoke(self.callback, **ctx.params)                                                                                                
	  File "/home/frappe/bench/env/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke                                              
		return callback(*args, **kwargs)                                                                                                              
	  File "/home/frappe/bench/apps/frappe/frappe/commands/utils.py", line 20, in build                                                               
		frappe.build.bundle(no_compress, make_copy=make_copy, restore = restore, verbose=verbose)                                                     
	  File "/home/frappe/bench/apps/frappe/frappe/build.py", line 34, in bundle                                                                       
		make_asset_dirs(make_copy=make_copy, restore=restore)                                                                                         
	  File "/home/frappe/bench/apps/frappe/frappe/build.py", line 104, in make_asset_dirs                                                             
		os.symlink(source, target)                                                                                                                    
	OSError: [Errno 2] No such file or directory                                                                                                      

Workaround, Check `./sites/assets`

	frappe@609ffc91c9aa:~/bench/sites/assets$ ls -al
	total 32
	drwxr-xr-x 2 root root 4096 Jun 18 17:16 .
	drwxr-xr-x 2 root root 4096 Jun 18 03:13 ..
	drwxr-xr-x 2 root root    0 May 30 16:41 css
	lrwxrwxrwx 1 root root   46 Jun 18 17:16 erpnext -> /home/frappe/bench/apps/erpnext/erpnext/public
	lrwxrwxrwx 1 root root   44 Jun 18 17:16 erpnext_docs -> /home/frappe/bench/apps/erpnext/erpnext/docs
	lrwxrwxrwx 1 root root   44 Jun 18 17:16 frappe -> /home/frappe/bench/apps/frappe/frappe/public
	lrwxrwxrwx 1 root root   42 Jun 18 17:16 frappe_docs -> /home/frappe/bench/apps/frappe/frappe/docs
	drwxr-xr-x 2 root root    0 May 30 16:41 js

There should have all of above, if you get 

	frappe@609ffc91c9aa:~/bench/sites/assets$ ls -la
	ls: cannot access 'frappe': No such file or directory
	total 24
	drwxr-xr-x 2 root root 4096 Jun 16 09:24 .
	drwxr-xr-x 2 root root 4096 Jun 18 03:13 ..
	drwxr-xr-x 2 root root    0 May 30 16:41 css
	lrwxrwxrwx 1 root root   46 Jun 16 09:24 erpnext -> /home/frappe/bench/apps/erpnext/erpnext/public
	lrwxrwxrwx 1 root root   44 Jun 16 09:24 erpnext_docs -> /home/frappe/bench/apps/erpnext/erpnext/docs
	-????????? ? ?    ?       ?            ? frappe
	lrwxrwxrwx 1 root root   42 Jun 16 09:24 frappe_docs -> /home/frappe/bench/apps/frappe/frappe/docs
	drwxr-xr-x 2 root root    0 May 30 16:41 js

Try restart docker after that,
`-????????? ? ?    ?       ?            ? frappe` this line should be gone
Then ran `ln -s /home/frappe/bench/apps/frappe/frappe/public frappe`

**Comment by pipech** [comment]
https://github.com/frappe/frappe/blob/a70d56fd04a1171b41f597f93bee40b34135cf67/frappe/build.py#L70

**Comment by pipech** [comment]
`bench update --build` is what cause this error

**Comment by pipech** [comment]
quick fix, comment out these line [(line 104-110)](https://github.com/frappe/frappe/blob/a70d56fd04a1171b41f597f93bee40b34135cf67/frappe/build.py#L104-L110) in `frappe/build.py`

	else:
		if os.path.exists(target):
			if os.path.islink(target):
				os.unlink(target)
			else:
				shutil.rmtree(target)
		os.symlink(source, target)
