### ISSUE TITLE
Build Error : AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by pipech** [pipech/erpnext-docker-debian#17]
The command '/bin/sh -c wget $easyinstallRepo     && python install.py     --without-bench-setup     && rm -rf bench     && git clone -b $benchBranch $benchRepo $benchPath      && sudo pip install -e $benchPath     && bench init $benchFolderName --frappe-path $frappeRepo --frappe-branch $frappeBranch --python $pythonVersion     && cd $benchFolderName     && sudo service mysql start     && bench new-site $siteName     --mariadb-root-password $mysqlPass      --admin-password $adminPass     && bench get-app erpnext $erpnextRepo --branch $erpnextBranch     && bench --site $siteName install-app erpnext     && bench switch-to-branch $branch     && bench update --patch     && mysql -u "root" "-p$mysqlPass" -e "CREATE USER '$remoteUser'@'%' IDENTIFIED BY '$remotePass';"     && mysql -u "root" "-p$mysqlPass" -e "GRANT ALL ON *.* TO '$remoteUser'@'%';"' returned a non-zero code: 1	

Traceback

	[91mTraceback (most recent call last):
	  File "/usr/local/bin/bench", line 11, in <module>
		load_entry_point('bench', 'console_scripts', 'bench')()
	  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
		bench_command()
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
	[0m
	[91m    return self.main(*args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
	[0m
	[91m    rv = self.invoke(ctx)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
	[0m
	[91m    return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
		return callback(*args, **kwargs)
	  File "/home/frappe/bench-repo/bench/commands/update.py", line 126, in switch_to_branch
		switch_to_branch(branch=branch, apps=list(apps), upgrade=upgrade)
	  File "/home/frappe/bench-repo/bench/app.py", line 394, in switch_to_branch
		switch_branch(branch, apps=apps, bench_path=bench_path, upgrade=upgrade)
	  File "/home/frappe/bench-repo/bench/app.py", line 362, in switch_branch
		version_upgrade = is_version_upgrade(app=app, bench_path=bench_path, branch=branch)
	  File "/home/frappe/bench-repo/bench/app.py", line 262, in is_version_upgrade
		upstream_version = get_upstream_version(app=app, branch=branch, bench_path=bench_path)
	  File "/home/frappe/bench-repo/bench/app.py", line 335, in get_upstream_version
		return get_version_from_string(contents)
	  File "/home/frappe/bench-repo/bench/app.py", line 405, in get_version_from_string
		return match.group(2)
	AttributeError: 'NoneType' object has no attribute 'group'

Full error log
* https://hub.docker.com/r/pipech/erpnext-docker-debian/builds/bwz97ymrb7qwcyrtcrrxaz8/
* https://hub.docker.com/r/pipech/erpnext-docker-debian/builds/bhydxdph7scapewstzdz6bd/
* https://hub.docker.com/r/pipech/erpnext-docker-debian/builds/bwz97ymrb7qwcyrtcrrxaz8/

**Comment by pipech** [comment]
Cause by `bench switch-to-branch $branch`

**Comment by pipech** [comment]
Fixed https://github.com/pipech/erpnext-docker-debian/releases/tag/v1.5.1
