### ISSUE TITLE
Production Setup #bench backup

### ISSUE THREAD

**Issue by minnhtutbagyi** [pipech/erpnext-docker-debian#45]
When trying to backup bench throw error. Please advise. Thanks in advance!

	root@03ec4aada0f2:/home/frappe/bench# bench backup
	Traceback (most recent call last):
	  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
		"__main__", mod_spec)
	  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
		exec(code, run_globals)
	  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
		main()
	  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
		click.Group(commands=commands)(prog_name='bench')
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
		return self.main(*args, **kwargs)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
		rv = self.invoke(ctx)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
		return callback(*args, **kwargs)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
		return f(get_current_context(), *args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
		ret = f(frappe._dict(ctx.obj), *args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/commands/site.py", line 302, in backup
		odb = scheduled_backup(ignore_files=not with_files, backup_path_db=backup_path_db, backup_path_files=backup_path_files, backup_path_private_files=backup_path_private_files, force=True)
	  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 170, in scheduled_backup
		odb = new_backup(older_than, ignore_files, backup_path_db=backup_path_db, backup_path_files=backup_path_files, force=force)
	  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 174, in new_backup
		delete_temp_backups(older_than = frappe.conf.keep_backups_for_hours or 24)
	  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 193, in delete_temp_backups
		os.remove(this_file_path)
	PermissionError: [Errno 13] Permission denied: './erpnext.com/private/backups/20190312_232916-zenboxallin_one-database.sql.gz'

**Comment by pipech** [comment]
Normally I use my own [backup utilities](https://github.com/pipech/erpnext-docker-debian/blob/master/frank) which will backup all persisting volume with all current docker configs.

Cons
 - Server will went down during backup time which will take about 5-10 minute.

Pros
 - If some thing went wrong you can spin-up new server using these files.

You should check that out.

**Comment by pipech** [comment]
I notice 2 things on your Traceback.

1. You should use `frappe` user not `root` user
2. Why did your site name `erpnext.com`

**Comment by minnhtutbagyi** [comment]
i am just started playing around with the erpnext and docker as my hobby.
my playground is win 10 and Frank backup is far from me so i am just try to `bench backup`.
as you recommend, will sure try Frank with VirtualBox. 
a bit shy to show my local site name and so replace with erpnext.com. (my apologies)
`frappe@e02fb37dc7be:~/bench$ bench backup`
Under frappe user also throw error same as under root.

**Comment by minnhtutbagyi** [comment]
after restart docker process, can be backup from both frappe and root. don't know why it happened. thanks for your valuable time. best regards.
