### ISSUE TITLE
REDIS error with Dev setup?

### ISSUE THREAD

**Issue by chris-hailstorm** [pipech/erpnext-docker-debian#52]
Using your instructions for Dev mode -- during the `. init.sh` step, I get this error. Any ideas?

	version: '2'

	services:
	  frappe:
		image: pipech/erpnext-docker-debian:mas-py3-latest
		ports:
		  - "8000-8005:8000-8005" #webserver_port
		  - "9000-9005:9000-9005" #socketio_port
		  - "6787:6787" #file_watcher_port
		volumes:
		  # persisting data
		  - ./data/bench/apps:/home/frappe/bench/apps
		  # config
		  - ./conf/frappe-docker-conf/init.sh:/home/frappe/bench/init.sh
		  - ./conf/frappe-docker-conf/init.sql:/home/frappe/bench/init.sql
		stdin_open: true
		tty: true
		command: tail -f /dev/null

	  mariadb:
		build: ./image/mariadb/.
		environment:
		  - MYSQL_USER=root
		  - MYSQL_ROOT_PASSWORD=mysql
		volumes:
		  # persisting data
		  - mariadb-data-volumes:/var/lib/mysql
		ports:
		  - "3306:3306"

	volumes:
	  mariadb-data-volumes:

----------------

	++ bench update --patch --no-backup
	Patching sites...
	Migrating dev32.loc
	Updating DocTypes for frappe        : [========================================]
	Updating DocTypes for erpnext       : [========================================]
	Traceback (most recent call last):
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 484, in connect
		sock = self._connect()
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 541, in _connect
		raise err
	...skipping...
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 529, in _connect
		sock.connect(socket_address)
	OSError: [Errno 99] Cannot assign requested address

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/client.py", line 667, in execute_command
		connection.send_command(*args)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 610, in send_command
		self.send_packed_command(self.pack_command(*args))
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 585, in send_packed_command
		self.connect()
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 489, in connect
		raise ConnectionError(self._error_message(e))
	redis.exceptions.ConnectionError: Error 99 connecting to localhost:13000. Cannot assign requested address.

**Comment by pipech** [comment]
Hi,

Could you try to start bench by running `bench start` ?

**Comment by chris-hailstorm** [comment]
Running `docker exec -it f7d53e44d271 bash -c 'bench start'` results in what looks like a normal startup with `redis_cache.1`, `redis_socketio.1` and `redis_queue.1` all running.

What are the implications of the `bench update --patch --no-backup` step failing?

**Comment by pipech** [comment]
Sorry, I don't know.

**Comment by aleksas** [comment]
`bench start` does solve the issue.
