### ISSUE TITLE
Build error: v10.x.x / python2

### ISSUE THREAD

**Issue by pipech** [pipech/erpnext-docker-debian#54]
Error message

	INFO:bench.app:getting app erpnext
	INFO:bench.utils:git clone https://github.com/frappe/erpnext --branch v10.x.x --depth 1 --origin upstream
	Cloning into 'erpnext'...
	Checking out files: 100% (6318/6318), done.
	INFO:bench.app:installing erpnext
	INFO:bench.utils:./env/bin/pip install -q  -e ./apps/erpnext 
	DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
	INFO:bench.utils:bench build --app erpnext
	Usage: bench  build [OPTIONS]
	Try "bench  build --help" for help.
	Error: no such option: --app
	('installing', u'erpnext')
	Traceback (most recent call last):
	  File "/usr/local/bin/bench", line 11, in <module>
		load_entry_point('bench', 'console_scripts', 'bench')()
	  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli
		bench_command()
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
		return self.main(*args, **kwargs)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
		rv = self.invoke(ctx)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
		return callback(*args, **kwargs)
	  File "/home/frappe/bench-repo/bench/commands/make.py", line 40, in get_app
		get_app(git_url, branch=branch)
	  File "/home/frappe/bench-repo/bench/app.py", line 140, in get_app
		build_assets(bench_path=bench_path, app=app_name)
	  File "/home/frappe/bench-repo/bench/utils.py", line 206, in build_assets
		exec_cmd(command, cwd=bench_path)
	  File "/home/frappe/bench-repo/bench/utils.py", line 159, in exec_cmd
		raise CommandFailedError(cmd)
	bench.utils.CommandFailedError: bench build --app erpnext

Travis
[#91 - 23/05/19](https://travis-ci.com/pipech/erpnext-docker-debian/builds/112612622)
[#92 - 28/05/19](https://travis-ci.com/pipech/erpnext-docker-debian/builds/113439807)

Cause by this line
https://github.com/frappe/bench/blob/92c17216f686759c882346b1864d5c0e81845dbc/bench/utils.py#L203-L206

Which call `bench build` with `--app` argument
https://github.com/frappe/frappe/blob/b0f9001c72a147921a118e868bb69158d2db969a/frappe/commands/utils.py#L15-L27

Which call `frappe.build.bundle` function
In version 11, 12 there is an `app` agrument in `frappe.build.bundle` function
https://github.com/frappe/frappe/blob/f75aa3beffe1639b999cb60e93707a494e6c61b3/frappe/build.py#L33-L47

But in version 10 there is no `app` agrument in `frappe.build.bundle` function
https://github.com/frappe/frappe/blob/3513e6b32ddc7aaec766fd9be976d20e049eab5b/frappe/build.py#L29-L42

**Comment by pipech** [comment]
https://github.com/frappe/frappe/pull/7581

**Comment by pipech** [comment]
https://github.com/frappe/frappe/pull/7615

**Comment by pipech** [comment]
Fixed: [#102](https://travis-ci.com/pipech/erpnext-docker-debian/builds/115128767)
