### ISSUE TITLE
Development Setup: DB access denied

### ISSUE THREAD

**Issue by aleksas** [pipech/erpnext-docker-debian#55]
Didn't change anything, just followed [this tutorial steps](https://pipech.github.io/erpnext-docker-debian/development_setup/) and got
`pymysql.err.OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'172.18.0.3' (using password: YES)")`

Related to [this issue](https://github.com/pipech/erpnext-docker-debian/issues/47), but no indication on how to solve it.
Tried to add anonymous user to DB in a DB docker suing `https://github.com/pipech/erpnext-docker-debian/issues/47` but I'd be surprised if it worked as I can't see erpnext database in the list.

FYI: running docker on Windows 10, but that shouldn't have an impact here.

**Comment by aleksas** [comment]
Switched to [tiral setup](https://pipech.github.io/erpnext-docker-debian/trial_setup/)

**Comment by pipech** [comment]
Hi,

In trial setup you should run `mysql -h mariadb -uroot -pmysql < "./init.sql"` in `home/frappe/bench` directory.

It will change the user and db host from `172.x.x.x` to `%`, it’ll make Frappe able to connect to mariadb when Frappe changes it's ip.

**Comment by chesterwu** [comment]
I am getting the same error with @aleksas as well! And I didn't change anything but just follow the tutorial. I wanna get the Development environment done. Can anyone help?
```
frappe@3f1fdc4e9342:~/bench$ . init.sh
++ sudo chown frappe:frappe apps
++ bench set-mariadb-host mariadb
++ bench config set-common-config -c root_password mysql
++ bench config set-common-config -c admin_password admin
++ cd apps
++ git clone https://github.com/frappe/frappe.git --branch master --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 2331, done.
remote: Counting objects: 100% (2331/2331), done.
remote: Compressing objects: 100% (2189/2189), done.
remote: Total 2331 (delta 359), reused 823 (delta 96), pack-reused 0
Receiving objects: 100% (2331/2331), 11.42 MiB | 5.48 MiB/s, done.
Resolving deltas: 100% (359/359), done.
++ git clone https://github.com/frappe/erpnext.git --branch master --depth 1 --origin upstream
Cloning into 'erpnext'...
remote: Enumerating objects: 5359, done.
remote: Counting objects: 100% (5359/5359), done.
remote: Compressing objects: 100% (4181/4181), done.
remote: Total 5359 (delta 1608), reused 2499 (delta 1062), pack-reused 0
Receiving objects: 100% (5359/5359), 14.93 MiB | 5.84 MiB/s, done.
Resolving deltas: 100% (1608/1608), done.
++ cd ..
++ bench update --requirements
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python3.5/site-packages (6.1.0)
WARNING: You are using pip version 19.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Backing up sites...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/commands/site.py", line 302, in backup
    odb = scheduled_backup(ignore_files=not with_files, backup_path_db=backup_path_db, backup_path_files=backup_path_files, backup_path_private_files=backup_path_private_files, force=True)
  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 170, in scheduled_backup
    odb = new_backup(older_than, ignore_files, backup_path_db=backup_path_db, backup_path_files=backup_path_files, force=force)
  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 180, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 48, in get_backup
    self.set_backup_file_name()
  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 61, in set_backup_file_name
    todays_date = now_datetime().strftime('%Y%m%d_%H%M%S')
  File "/home/frappe/bench/apps/frappe/frappe/utils/data.py", line 126, in now_datetime
    dt = convert_utc_to_user_timezone(datetime.datetime.utcnow())
  File "/home/frappe/bench/apps/frappe/frappe/utils/data.py", line 149, in convert_utc_to_user_timezone
    return utcnow.astimezone(timezone(get_time_zone()))
  File "/home/frappe/bench/apps/frappe/frappe/utils/data.py", line 143, in get_time_zone
    return frappe.cache().get_value("time_zone", _get_time_zone)
  File "/home/frappe/bench/apps/frappe/frappe/utils/redis_wrapper.py", line 79, in get_value
    val = generator()
  File "/home/frappe/bench/apps/frappe/frappe/utils/data.py", line 137, in _get_time_zone
    return frappe.db.get_system_setting('time_zone') or 'Asia/Kolkata' # Default to India ?!
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 950, in get_system_setting
    return frappe.cache().get_value("system_settings", _load_system_settings).get(key)
  File "/home/frappe/bench/apps/frappe/frappe/utils/redis_wrapper.py", line 79, in get_value
    val = generator()
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 949, in _load_system_settings
    return self.get_singles_dict("System Settings")
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 610, in get_singles_dict
    """, doctype)
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'172.18.0.3' (using password: YES)")
```

**Comment by rajvijen** [comment]
@pipech @aleksas I am trying to use **development setup**. Getting same error at the time of back-site in the execution of init.sh file in the running container. 
Could you please help to update the depreciated development setup, as not all developers want to use a VSCode setup, instead of vim based terminal editor?

**System Specs:-**
Running on EC2 instance via SSH
Ubuntu 18.04 LTS
