### ISSUE TITLE
[v12] Build error

### ISSUE THREAD

**Issue by pipech** [pipech/erpnext-docker-debian#68]
First occurrence: [Build #128](https://travis-ci.com/pipech/erpnext-docker-debian/builds/133010760) [2019-10-23]
Last success built: v12.0.16 [2019-10-15]

	Reading package lists...
	Building dependency tree...
	Reading state information...
	The following packages will be REMOVED:
	  guile-2.0-libs* libfribidi0* libgc1c2* libgsasl7* libkyotocabinet16v5*
	  libltdl7* liblzo2-2* libmailutils5* libntlm0* libpython2.7* mailutils*
	  mailutils-common*
	0 upgraded, 0 newly installed, 12 to remove and 12 not upgraded.
	After this operation, 23.2 MB disk space will be freed.
	(Reading database ... 39596 files and directories currently installed.)
	Removing mailutils (1:3.1.1-1) ...
	Removing libmailutils5:amd64 (1:3.1.1-1) ...
	Removing guile-2.0-libs:amd64 (2.0.13+1-4) ...
	Removing libfribidi0:amd64 (0.19.7-1+deb9u1) ...
	Removing libgc1c2:amd64 (1:7.4.2-8) ...
	Removing libgsasl7 (1.8.0-8+b2) ...
	Removing libkyotocabinet16v5:amd64 (1.2.76-4.2+b1) ...
	Removing libltdl7:amd64 (2.4.6-2) ...
	Removing liblzo2-2:amd64 (2.08-1.2+b2) ...
	Removing libntlm0:amd64 (1.4-8) ...
	Removing libpython2.7:amd64 (2.7.13-2+deb9u3) ...
	Removing mailutils-common (1:3.1.1-1) ...
	Processing triggers for libc-bin (2.24-11+deb9u3) ...
	Starting MariaDB database server: mysqld already running.
	Creating Database...
	Installing frappe...
	Updating DocTypes for frappe        : [========================================]Traceback (most recent call last):
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 484, in connect
		sock = self._connect()
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 541, in _connect
		raise err
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 529, in _connect
		sock.connect(socket_address)
	OSError: [Errno 99] Cannot assign requested address
	During handling of the above exception, another exception occurred:
	Traceback (most recent call last):
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/client.py", line 2879, in execute
		return execute(conn, stack, raise_on_error)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/client.py", line 2749, in _execute_transaction
		connection.send_packed_command(all_cmds)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 585, in send_packed_command
		self.connect()
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 489, in connect
		raise ConnectionError(self._error_message(e))
	redis.exceptions.ConnectionError: Error 99 connecting to localhost:11000. Cannot assign requested address.
	During handling of the above exception, another exception occurred:
	Traceback (most recent call last):
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 484, in connect
		sock = self._connect()
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 541, in _connect
		raise err
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 529, in _connect
		sock.connect(socket_address)
	OSError: [Errno 99] Cannot assign requested address
	During handling of the above exception, another exception occurred:
	Traceback (most recent call last):
	  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
		"__main__", mod_spec)
	  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
		exec(code, run_globals)
	  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
		main()
	  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
		click.Group(commands=commands)(prog_name='bench')
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
		return self.main(*args, **kwargs)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
		rv = self.invoke(ctx)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
		return _process_result(sub_ctx.command.invoke(sub_ctx))
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
		return ctx.invoke(self.callback, **ctx.params)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
		return callback(*args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/commands/site.py", line 32, in new_site
		db_type=db_type)
	  File "/home/frappe/bench/apps/frappe/frappe/commands/site.py", line 73, in _new_site
		_install_app(app, verbose=verbose, set_as_patched=not source_sql)
	  File "/home/frappe/bench/apps/frappe/frappe/installer.py", line 92, in install_app
		frappe.get_attr(after_install)()
	  File "/home/frappe/bench/apps/frappe/frappe/utils/install.py", line 19, in after_install
		install_basic_docs()
	  File "/home/frappe/bench/apps/frappe/frappe/utils/install.py", line 77, in install_basic_docs
		frappe.get_doc(d).insert()
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 259, in insert
		self.run_post_save_methods()
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 919, in run_post_save_methods
		self.run_method("on_update")
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 787, in run_method
		out = Document.hook(fn)(self, *args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 1058, in composer
		return composed(self, method, *args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 1041, in runner
		add_to_return_value(self, fn(self, *args, **kwargs))
	  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 781, in <lambda>
		fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/core/doctype/user/user.py", line 93, in on_update
		self.share_with_self()
	  File "/home/frappe/bench/apps/frappe/frappe/core/doctype/user/user.py", line 177, in share_with_self
		flags={"ignore_share_permission": True})
	  File "/home/frappe/bench/apps/frappe/frappe/share.py", line 44, in add
		notify_assignment(user, doctype, name, everyone)
	  File "/home/frappe/bench/apps/frappe/frappe/share.py", line 171, in notify_assignment
		enqueue_create_notification(shared_by, notification_doc)
	  File "/home/frappe/bench/apps/frappe/frappe/desk/doctype/notification_log/notification_log.py", line 38, in enqueue_create_notification
		now=frappe.flags.in_test
	  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1475, in enqueue
		return frappe.utils.background_jobs.enqueue(*args, **kwargs)
	  File "/home/frappe/bench/apps/frappe/frappe/utils/background_jobs.py", line 69, in enqueue
		kwargs=queue_args)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/rq/queue.py", line 258, in enqueue_call
		job = self.enqueue_job(job, at_front=at_front)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/rq/queue.py", line 331, in enqueue_job
		pipe.execute()
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/client.py", line 2894, in execute
		return execute(conn, stack, raise_on_error)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/client.py", line 2749, in _execute_transaction
		connection.send_packed_command(all_cmds)
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 585, in send_packed_command
		self.connect()
	  File "/home/frappe/bench/env/lib/python3.5/site-packages/redis/connection.py", line 489, in connect
		raise ConnectionError(self._error_message(e))
	redis.exceptions.ConnectionError: Error 99 connecting to localhost:11000. Cannot assign requested address.
	The command '/bin/sh -c sudo service mysql start     && mysql --user="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'travis';"     && git clone $benchRepo /tmp/.bench --depth 1 --branch $benchBranch     && wget $easyinstallRepo     && sed -i '/mariadb/d' /tmp/.bench/playbooks/site.yml     && python install.py     --without-bench-setup     && rm -rf bench     && git clone --branch $benchBranch --depth 1 --origin upstream $benchRepo $benchPath      && sudo pip install -e $benchPath     && bench init $benchFolderName --frappe-path $frappeRepo --frappe-branch $appBranch --python $pythonVersion     && cd $benchFolderName     && bench get-app erpnext $erpnextRepo --branch $appBranch     && bench update --patch     && rm -rf     apps/frappe_io     apps/foundation     && sed -i '/foundation\|frappe_io/d' sites/apps.txt     && sudo rm -rf /tmp/*     && sudo apt-get autoremove --purge -y     && sudo apt-get clean     && sudo service mysql start     && bench new-site $siteName     --mariadb-root-password $mysqlPass      --admin-password $adminPass     && bench --site $siteName install-app erpnext' returned a non-zero code: 1
	The command ".travis/build_image.sh" failed and exited with 1 during .

**Comment by pipech** [comment]
`bench new-site` command run pass `install_db` function and error on `_install_app` function

**Comment by pipech** [comment]
[enqueue_create_notification](https://github.com/frappe/frappe/blob/0b03e9b70ec97971f29cc8ede79b651588a31a93/frappe/desk/doctype/notification_log/notification_log.py#L28)

**Comment by pipech** [comment]
[enqueue](https://github.com/frappe/frappe/blob/version-12/frappe/utils/background_jobs.py#L24)

**Comment by pipech** [comment]
Sooooo, it might be redis configuration but why does it only occur on version 12 ???

**Comment by pipech** [comment]
https://discuss.erpnext.com/t/new-site-error-v12-0-17/54332/12

**Comment by carstenblt** [comment]
https://github.com/frappe/erpnext/issues/19486

Adding
`&& sed -i -e 's/cryptography ansible pip/cryptography ansible==2.8.5.0 pip/g' install.py \`
after
`&& wget $easyinstallRepo \`
fixes it. But it's an upstream bug...

**Comment by pipech** [comment]
https://github.com/frappe/erpnext/issues/19486#issuecomment-549182188

**Comment by pipech** [comment]
https://travis-ci.com/pipech/erpnext-docker-debian/builds/136138756

Develop branch is already fix by upstream.

**Comment by pipech** [comment]
Fixed by upstream.

https://travis-ci.com/pipech/erpnext-docker-debian/builds/137206256
