### ISSUE TITLE
Error: Value missing for Opportunity: Company (Contact Us form)

### ISSUE THREAD

**Issue by garyritchie** [pipech/erpnext-docker-debian#78]
I get this error when submitting the build-in Contact Us form.

Migration from v10 to v12. Most everything works but this issue I'm unable to solve so far:

```
website.js:161 Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1042, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench/apps/erpnext/erpnext/templates/utils.py", line 45, in send_message
    opportunity.insert(ignore_permissions=True)
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 230, in insert
    self._validate()
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 460, in _validate
    self._validate_mandatory()
  File "/home/frappe/bench/apps/frappe/frappe/model/document.py", line 740, in _validate_mandatory
    name=self.name))
frappe.exceptions.MandatoryError: [Opportunity, OPTY-00053]: company

process_response @ website.js:161
```

**Comment by pipech** [comment]
Hi.

I think this is bug from Frappe apps you should open issues there.
https://github.com/frappe/frappe

**Comment by garyritchie** [comment]
Opened issue here: https://github.com/frappe/frappe/issues/9078
