### ISSUE TITLE
Build Error #140+

### ISSUE THREAD

**Issue by pipech** [pipech/erpnext-docker-debian#80]
Error on all config v10, v11, v12 and python2, python3.

[Install.py history](https://github.com/frappe/bench/commits/master/playbooks/install.py)

First occurrence: [build#140 ](https://travis-ci.com/pipech/erpnext-docker-debian/builds/142751749) - 31/12/2019

	Step 14/23 : ARG appBranch=master
	 ---> Running in ea5afa721657
	Removing intermediate container ea5afa721657
	 ---> d9d0edbcad13
	Step 15/23 : RUN sudo service mysql start     && mysql --user="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'travis';"     && git clone $benchRepo /tmp/.bench --depth 1 --branch $benchBranch     && wget $easyinstallRepo     && sed -i '/mariadb/d' /tmp/.bench/playbooks/site.yml     && python install.py     --without-bench-setup     && rm -rf bench     && git clone --branch $benchBranch --depth 1 --origin upstream $benchRepo $benchPath      && sudo pip install -e $benchPath     && bench init $benchFolderName --frappe-path $frappeRepo --frappe-branch $appBranch --python $pythonVersion     && cd $benchFolderName     && bench get-app erpnext $erpnextRepo --branch $appBranch     && bench update --patch     && rm -rf     apps/frappe_io     apps/foundation     && sed -i '/foundation\|frappe_io/d' sites/apps.txt     && sudo rm -rf /tmp/*     && sudo apt-get autoremove --purge -y     && sudo apt-get clean     && sudo service mysql start     && bench new-site $siteName     --mariadb-root-password $mysqlPass      --admin-password $adminPass     && bench --site $siteName install-app erpnext
	 ---> Running in 14a11a9a4938
	Starting MariaDB database server: mysqld.
	Cloning into '/tmp/.bench'...
	--2019-12-31 14:30:14--  https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
	Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
	Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 14578 (14K) [text/plain]
	Saving to: ‘install.py’
		 0K .......... ....                                       100% 1.34M=0.01s
	2019-12-31 14:30:15 (1.34 MB/s) - ‘install.py’ saved [14578/14578]
	Please run this script as a non-root user with sudo privileges
	Cloning into 'bench-repo'...
	sudo: pip: command not found
	The command '/bin/sh -c sudo service mysql start     && mysql --user="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'travis';"     && git clone $benchRepo /tmp/.bench --depth 1 --branch $benchBranch     && wget $easyinstallRepo     && sed -i '/mariadb/d' /tmp/.bench/playbooks/site.yml     && python install.py     --without-bench-setup     && rm -rf bench     && git clone --branch $benchBranch --depth 1 --origin upstream $benchRepo $benchPath      && sudo pip install -e $benchPath     && bench init $benchFolderName --frappe-path $frappeRepo --frappe-branch $appBranch --python $pythonVersion     && cd $benchFolderName     && bench get-app erpnext $erpnextRepo --branch $appBranch     && bench update --patch     && rm -rf     apps/frappe_io     apps/foundation     && sed -i '/foundation\|frappe_io/d' sites/apps.txt     && sudo rm -rf /tmp/*     && sudo apt-get autoremove --purge -y     && sudo apt-get clean     && sudo service mysql start     && bench new-site $siteName     --mariadb-root-password $mysqlPass      --admin-password $adminPass     && bench --site $siteName install-app erpnext' returned a non-zero code: 1
	The command ".travis/build_image.sh" failed and exited with 1 during .
	Your build has been stopped.

[Build #141](https://travis-ci.com/pipech/erpnext-docker-debian/builds/143402462)

	Step 14/23 : ARG appBranch=master
	 ---> Running in f1dff4d3c0c6
	Removing intermediate container f1dff4d3c0c6
	 ---> 526813de92c3
	Step 15/23 : RUN sudo service mysql start     && mysql --user="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'travis';"     && git clone $benchRepo /tmp/.bench --depth 1 --branch $benchBranch     && wget $easyinstallRepo     && sed -i '/mariadb/d' /tmp/.bench/playbooks/site.yml     && python install.py     --without-bench-setup     && rm -rf bench     && git clone --branch $benchBranch --depth 1 --origin upstream $benchRepo $benchPath      && sudo pip install -e $benchPath     && bench init $benchFolderName --frappe-path $frappeRepo --frappe-branch $appBranch --python $pythonVersion     && cd $benchFolderName     && bench get-app erpnext $erpnextRepo --branch $appBranch     && bench update --patch     && rm -rf     apps/frappe_io     apps/foundation     && sed -i '/foundation\|frappe_io/d' sites/apps.txt     && sudo rm -rf /tmp/*     && sudo apt-get autoremove --purge -y     && sudo apt-get clean     && sudo service mysql start     && bench new-site $siteName     --mariadb-root-password $mysqlPass      --admin-password $adminPass     && bench --site $siteName install-app erpnext
	 ---> Running in abe551e0c02c
	Starting MariaDB database server: mysqld.
	Cloning into '/tmp/.bench'...
	--2020-01-07 14:32:54--  https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
	Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
	Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 14207 (14K) [text/plain]
	Saving to: ‘install.py’
		 0K .......... ...                                        100% 1.16M=0.01s
	2020-01-07 14:32:54 (1.16 MB/s) - ‘install.py’ saved [14207/14207]
	Traceback (most recent call last):
	  File "install.py", line 386, in <module>
		if not raw_input("It is recommended to run this script with Python 3\nDo you still wish to continue? [Y/n]: ").lower() == "y":
	EOFError: EOF when reading a line
	It is recommended to run this script with Python 3
	Do you still wish to continue? [Y/n]: The command '/bin/sh -c sudo service mysql start     && mysql --user="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'travis';"     && git clone $benchRepo /tmp/.bench --depth 1 --branch $benchBranch     && wget $easyinstallRepo     && sed -i '/mariadb/d' /tmp/.bench/playbooks/site.yml     && python install.py     --without-bench-setup     && rm -rf bench     && git clone --branch $benchBranch --depth 1 --origin upstream $benchRepo $benchPath      && sudo pip install -e $benchPath     && bench init $benchFolderName --frappe-path $frappeRepo --frappe-branch $appBranch --python $pythonVersion     && cd $benchFolderName     && bench get-app erpnext $erpnextRepo --branch $appBranch     && bench update --patch     && rm -rf     apps/frappe_io     apps/foundation     && sed -i '/foundation\|frappe_io/d' sites/apps.txt     && sudo rm -rf /tmp/*     && sudo apt-get autoremove --purge -y     && sudo apt-get clean     && sudo service mysql start     && bench new-site $siteName     --mariadb-root-password $mysqlPass      --admin-password $adminPass     && bench --site $siteName install-app erpnext' returned a non-zero code: 1
	The command ".travis/build_image.sh" failed and exited with 1 during .
	Your build has been stopped.

[Build #142](https://travis-ci.com/pipech/erpnext-docker-debian/builds/144338507), [Build #143](https://travis-ci.com/pipech/erpnext-docker-debian/builds/145376544), [Build #144](https://travis-ci.com/pipech/erpnext-docker-debian/builds/146403022)

	Step 15/23 : RUN sudo service mysql start     && mysql --user="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'travis';"     && git clone $benchRepo /tmp/.bench --depth 1 --branch $benchBranch     && wget $easyinstallRepo     && sed -i '/mariadb/d' /tmp/.bench/playbooks/site.yml     && python install.py     --without-bench-setup     && rm -rf bench     && git clone --branch $benchBranch --depth 1 --origin upstream $benchRepo $benchPath      && sudo pip install -e $benchPath     && bench init $benchFolderName --frappe-path $frappeRepo --frappe-branch $appBranch --python $pythonVersion     && cd $benchFolderName     && bench get-app erpnext $erpnextRepo --branch $appBranch     && bench update --patch     && rm -rf     apps/frappe_io     apps/foundation     && sed -i '/foundation\|frappe_io/d' sites/apps.txt     && sudo rm -rf /tmp/*     && sudo apt-get autoremove --purge -y     && sudo apt-get clean     && sudo service mysql start     && bench new-site $siteName     --mariadb-root-password $mysqlPass      --admin-password $adminPass     && bench --site $siteName install-app erpnext
	 ---> Running in 2f0f391a0cb5
	Starting MariaDB database server: mysqld.
	Cloning into '/tmp/.bench'...
	--2020-01-14 14:33:32--  https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
	Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
	Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 14831 (14K) [text/plain]
	Saving to: ‘install.py’
		 0K .......... ....                                       100% 1.18M=0.01s
	2020-01-14 14:33:32 (1.18 MB/s) - ‘install.py’ saved [14831/14831]
	  File "install.py", line 35
		print("Install script run at {0} on {1}\n\n".format(execution_time, execution_day), file=log_stream)
																								^
	SyntaxError: invalid syntax
	The command '/bin/sh -c sudo service mysql start     && mysql --user="root" --execute="ALTER USER 'root'@'localhost' IDENTIFIED BY 'travis';"     && git clone $benchRepo /tmp/.bench --depth 1 --branch $benchBranch     && wget $easyinstallRepo     && sed -i '/mariadb/d' /tmp/.bench/playbooks/site.yml     && python install.py     --without-bench-setup     && rm -rf bench     && git clone --branch $benchBranch --depth 1 --origin upstream $benchRepo $benchPath      && sudo pip install -e $benchPath     && bench init $benchFolderName --frappe-path $frappeRepo --frappe-branch $appBranch --python $pythonVersion     && cd $benchFolderName     && bench get-app erpnext $erpnextRepo --branch $appBranch     && bench update --patch     && rm -rf     apps/frappe_io     apps/foundation     && sed -i '/foundation\|frappe_io/d' sites/apps.txt     && sudo rm -rf /tmp/*     && sudo apt-get autoremove --purge -y     && sudo apt-get clean     && sudo service mysql start     && bench new-site $siteName     --mariadb-root-password $mysqlPass      --admin-password $adminPass     && bench --site $siteName install-app erpnext' returned a non-zero code: 1
	The command ".travis/build_image.sh" failed and exited with 1 during .
	Your build has been stopped.

**Comment by pipech** [comment]
Fixed by adding `sudo` and change `python` to `python3`
https://discuss.erpnext.com/t/install-failed-ubuntu-18-04/56898/6
