### ISSUE TITLE
Production setup - Cant finish setup wizard

### ISSUE THREAD

**Issue by shmouu** [pipech/erpnext-docker-debian#82]
Cant finish the setup wizard.
At the last step it just timeouts and says following:

Request Timed Out
Could not start up: Error in setup

api/method/frappe.desk.page.setup_wizard.setup_wizard.setup_complete 504

Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1042, in call
    return fn(*args, **newargs)
TypeError: setup_complete() missing 1 required positional argument: 'args'

**Comment by wildsurfer** [comment]
Looks like this issue: https://discuss.erpnext.com/t/startup-wizard-fails-while-inserting-property-setter-py-values/57952/27

**Comment by pipech** [comment]
Per wildsurfer comment you should try

```
bench --site SITE_NAME reinstall
bench get-app --branch version-12 erpnext
bench --site SITE_NAME install-app erpnext
```

Or I've just create new image with new installation process (without using easyinstall script) you should check that out, I've tried and can complete Setup wizard.

Tag `12.4.3-py3`

**Comment by shmouu** [comment]
Thank you guys.  It worked with the new version.
