### ISSUE TITLE
Access denied for user

### ISSUE THREAD

**Issue by paulb-opusvl** [pipech/erpnext-docker-debian#88]
Trying to setup a development system and failing during the `. init.sh`

I followed a previous issue and ran the `initsql` and still have a problem where it seems to be using a user account that does not exist in mariadb.

```shell
frappe@28faae800b22:~/bench$ mysql -h mariadb -uroot -pmysql < init.sql 
frappe@28faae800b22:~/bench$ . init.sh
++ sudo chown frappe:frappe apps
++ bench set-mariadb-host mariadb
++ bench config set-common-config -c root_password mysql
++ bench config set-common-config -c admin_password admin
++ cd apps
++ git clone https://github.com/frappe/frappe.git --branch master --depth 1 --origin upstream
Cloning into 'frappe'...
remote: Enumerating objects: 2331, done.
remote: Counting objects: 100% (2331/2331), done.
remote: Compressing objects: 100% (2189/2189), done.
remote: Total 2331 (delta 360), reused 839 (delta 96), pack-reused 0
Receiving objects: 100% (2331/2331), 11.42 MiB | 5.25 MiB/s, done.
Resolving deltas: 100% (360/360), done.
++ git clone https://github.com/frappe/erpnext.git --branch master --depth 1 --origin upstream
Cloning into 'erpnext'...
remote: Enumerating objects: 5359, done.
remote: Counting objects: 100% (5359/5359), done.
remote: Compressing objects: 100% (4250/4250), done.
remote: Total 5359 (delta 1594), reused 2456 (delta 993), pack-reused 0
Receiving objects: 100% (5359/5359), 14.94 MiB | 8.69 MiB/s, done.
Resolving deltas: 100% (1594/1594), done.
++ cd ..
++ bench update --requirements
INFO:bench.utils:./env/bin/pip install Pillow
Requirement already satisfied: Pillow in ./env/lib/python3.5/site-packages (6.1.0)
WARNING: You are using pip version 19.1.1, however version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Backing up sites...
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/commands/site.py", line 302, in backup
    odb = scheduled_backup(ignore_files=not with_files, backup_path_db=backup_path_db, backup_path_files=backup_path_files, backup_path_private_files=backup_path_private_files, force=True)
  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 170, in scheduled_backup
    odb = new_backup(older_than, ignore_files, backup_path_db=backup_path_db, backup_path_files=backup_path_files, force=force)
  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 180, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 48, in get_backup
    self.set_backup_file_name()
  File "/home/frappe/bench/apps/frappe/frappe/utils/backups.py", line 61, in set_backup_file_name
    todays_date = now_datetime().strftime('%Y%m%d_%H%M%S')
  File "/home/frappe/bench/apps/frappe/frappe/utils/data.py", line 126, in now_datetime
    dt = convert_utc_to_user_timezone(datetime.datetime.utcnow())
  File "/home/frappe/bench/apps/frappe/frappe/utils/data.py", line 149, in convert_utc_to_user_timezone
    return utcnow.astimezone(timezone(get_time_zone()))
  File "/home/frappe/bench/apps/frappe/frappe/utils/data.py", line 143, in get_time_zone
    return frappe.cache().get_value("time_zone", _get_time_zone)
  File "/home/frappe/bench/apps/frappe/frappe/utils/redis_wrapper.py", line 79, in get_value
    val = generator()
  File "/home/frappe/bench/apps/frappe/frappe/utils/data.py", line 137, in _get_time_zone
    return frappe.db.get_system_setting('time_zone') or 'Asia/Kolkata' # Default to India ?!
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 950, in get_system_setting
    return frappe.cache().get_value("system_settings", _load_system_settings).get(key)
  File "/home/frappe/bench/apps/frappe/frappe/utils/redis_wrapper.py", line 79, in get_value
    val = generator()
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 949, in _load_system_settings
    return self.get_singles_dict("System Settings")
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 610, in get_singles_dict
    """, doctype)
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user '1bd3e0294da19198'@'10.0.1.4' (using password: YES)")
```

**Comment by pipech** [comment]
Try to run this line by line.

mysql -h mariadb -uroot -pmysql
UPDATE mysql.user SET host = '10.%.%.%' WHERE host LIKE '10.%.%.%' AND user != 'root';
UPDATE mysql.db SET host = '10.%.%.%' WHERE host LIKE '10.%.%.%' AND user != 'root';
FLUSH PRIVILEGES;
