### ISSUE TITLE
Root PWD not working development_setup_vscode

### ISSUE THREAD

**Issue by ARAGATO** [pipech/erpnext-docker-debian#91]
Fresh setup of development_setup_vscode.
Trying to drop site1.local via bench drop-site site1.local.
Getting error access denied:

```
frappe@981a21ee7fcc:~/bench$ bench drop-site site1.local
Backed up files /home/frappe/bench/sites/site1.local/private/backups/20200430_163410-site1_local-files.tar
Backed up files /home/frappe/bench/sites/site1.local/private/backups/20200430_163410-site1_local-private-files.tar
MySQL root password: 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/bench/apps/frappe/frappe/commands/site.py", line 350, in drop_site
    _drop_site(site, root_login, root_password, archived_sites_path, force)
  File "/home/frappe/bench/apps/frappe/frappe/commands/site.py", line 381, in _drop_site
    dbman.delete_user(db_name)
  File "/home/frappe/bench/apps/frappe/frappe/model/db_schema.py", line 516, in delete_user
    host = self.get_current_host()
  File "/home/frappe/bench/apps/frappe/frappe/model/db_schema.py", line 482, in get_current_host
    return self.db.sql("select user()")[0][0].split('@')[1]
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 165, in sql
    self.connect()
  File "/home/frappe/bench/apps/frappe/frappe/database.py", line 115, in connect
    charset='utf8mb4', use_unicode = True, conv = conversions, local_infile = self.local_infile)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/bench/env/lib/python3.5/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
```

Tried with 12345 as written in readme and double checked with Dockerfile.
Also, why is site1.local still on ERPNext 11.x? Because it was never updated right?
However, new-site does not work, too because of same error.

**Comment by ARAGATO** [comment]
`mysql -u root -p` does not work, too.
Somehow the password got not set or set to a different value.

**Comment by ARAGATO** [comment]
Looked through the docker image history of mas-py3-latest and found that the password is not 12345 but travis.
