### ISSUE TITLE
"Setup failed. Could not start up: Error in setup" in setup wizard

### ISSUE THREAD

**Issue by JohnVeness** [pipech/erpnext-docker-debian#98]
Hi, many thanks for this project.

I pulled the pipech/erpnext-docker-debian:v12-py3-latest image (Digest: sha256:076ae76171bc753a561f2e5936f9cc3d3e5b747f085369c75af9291858105949) and ran it following the instructions in https://github.com/pipech/erpnext-docker-debian/wiki/Trial-Setup

When accessing the localhost:8000 address, I logon as Administrator and see the setup wizard. I'm not sure if it matters what I filled in (I have tried a few variations with no difference), but for the record I answered:

- Language: English
- Country: United Kingdom (and the default TZ and currency for that)
- my name, email address, password
- Selected just Services domain
- Company: "Veness", abbreviation: "V"
- What does it do?: "V"
- Chart of accounts: Standard
- Financial year: 01-04-2020 to 31-03-2021

It then displays: 
```
Setting up your system

Starting Frappe ...
```

for a minute, then:

```
Setup failed

Could not start up: Error in setup
```

Any ideas?

**Comment by garyritchie** [comment]
Hey John, if you're able to get something from the docker container logs,
that would be helpful. See:
https://docs.docker.com/engine/reference/commandline/service_logs/

I believe the abbreviation is primarily for the Chart of Accounts. Each
account will be named: *[Account Name] - V*
This proves important if you're managing multiple companies.

**Comment by JohnVeness** [comment]
Haha, I wasn't actually asking what the abbreviation was for, but I see why you think that! When I said 'What does it do?: "V"', I just meant that I typed in "V" as the answer to the "What does it do?" question! I couldn't think what to type (and it doesn't allow blanks), so just typed "V".
![image](https://user-images.githubusercontent.com/2512915/87882916-77aca980-c9fb-11ea-81db-38b134e38079.png)

Anyway, I couldn't get anything useful from the docker logs (that page you linked is just for when using a swarm, which I'm not doing in "trial" mode). However, I exec'd /bin/bash in the container and looked at ~/bench/logs/frappe.log, which contained:

```
[ERROR] 2020-07-19 19:18:26,518 | /home/frappe/bench/apps/frappe/frappe/app.py:
Site: site1.local
Form Dict: {
 "cmd": "frappe.realtime.get_user_info"
}
Request Error
Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 63, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1054, in call
    return fn(*args, **newargs)
TypeError: get_user_info() missing 1 required positional argument: 'sid'
[ERROR] 2020-07-19 19:18:26,872 | /home/frappe/bench/apps/frappe/frappe/utils/error.py:
New Exception collected with id: 2020-07-19 19:18:26.519047-127.0.0.1-3f4
[DEBUG] 2020-07-19 19:24:25,327 | /home/frappe/bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local
[DEBUG] 2020-07-19 19:25:25,663 | /home/frappe/bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Queued events for site site1.local

```

Same error happens with pipech/erpnext-docker-debian:12.7.3-py3, by the way.

**Comment by pipech** [comment]
I've tried and can (sort-of) replicate the error.

I'm using `pipech/erpnext-docker-debian:12.7.3-py3` but i got these error.

```
[ERROR] 2020-07-20 01:55:48,606 | /home/frappe/bench/apps/frappe/frappe/utils/scheduler.py:
Site: site1.local
Exception in Enqueue Events for Site site1.local
Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/utils/scheduler.py", line 84, in enqueue_events_for_site
    enqueue_events(site=site, queued_jobs=queued_jobs)
  File "/home/frappe/bench/apps/frappe/frappe/utils/scheduler.py", line 105, in enqueue_events
    update_modified=False)
  File "/home/frappe/bench/apps/frappe/frappe/database/database.py", line 662, in set_value
    list(keys) + [dt], debug=debug)
  File "/home/frappe/bench/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/frappe/bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/frappe/bench/env/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/frappe/bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/frappe/bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/frappe/bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/frappe/bench/env/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/frappe/bench/env/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/frappe/bench/env/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
```

I'll leave it be for now because some time it's ERPNext/Frappe bug and it'll get fixed by it self.

For now you could use version `12.9.4-py3`.

**Comment by JohnVeness** [comment]
Thanks, 12.9.4 seems to work :+1:

**Comment by pipech** [comment]
Fixed with latest version `12-F8.4_E10.1-py3`
